channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=2
- nodejs=11
- nbconvert=5.5
- widgetsnbextension=3.5
# Python Kernel
- python=3.8
- ipykernel
- ipywidgets
- altair
- bqplot
- dask
- matplotlib>=3.1
- pandas>=1
- scikit-learn
- seaborn
- pyyaml